### ISSUE TITLE
ForgeModLoader crash [Server build]

### ISSUE THREAD

**Issue by ErythroCraft** [rheimus/serversync-forge-loader#10]
ForgeModLoader 1.18.2-40.1.0
ServerSyncForgeLoader: 2.1.0

#### ClientSide:
1. I placed this mod in the mods folder.
2. GameLauncher crashed

#### ServerSide:
1. I placed this mod in the mods folder.
2. Server crashed

#### ServerLog: 
[debug.log](https://github.com/rheimus/serversync-forge-loader/files/8738340/debug.log)
[latest.log](https://github.com/rheimus/serversync-forge-loader/files/8738341/latest.log)
[serversync-SERVER.log](https://github.com/rheimus/serversync-forge-loader/files/8738342/serversync-SERVER.log)

#### ClientLog: 
[latest.log](https://github.com/rheimus/serversync-forge-loader/files/8738300/latest.log)
[serversync-CLIENT.log](https://github.com/rheimus/serversync-forge-loader/files/8738326/serversync-CLIENT.log)

**Comment by rheimus** [comment]
Looks like forge changed the mod loading rules again, will need an update to work on 1.18

**Comment by ErythroCraft** [comment]
Do you want create an update?
I know, many people will liking this.

Maybe 1.18.x + 1.19.x ??

**Comment by rheimus** [comment]
I will most likely eventually get to updating this for 1.17-current, I have very little time at the moment to re-learn all the forge setup needed though, it is unfortunately not the simplest devkit to work with. If you know of a good way to find a list of the forge version strings that would be useful.

Code probably does not need to change other than fiddling with whatever values the forge interface has changed over the versions and changing the gradle setup to point to the appropriate forge & minecraft versions.

The logs seem to be complaining about using hyphens instead of underscores for the modID, regex pattern has been set to lowercase letters, numbers and underscore that can not start with a number.
```
serversync-forge-loader does not match the standard: ^[a-z][a-z0-9_]{1,63}$
```

**Comment by ErythroCraft** [comment]
I am not sure.
But maybe this can help you.

[Semantic - 2.0](https://semver.org/spec/v2.0.0.html)
[Semantic Versioning Specification](https://github.com/semver/semver)

And here is what most people use to setup multiversions and more.
[pahimar](https://github.com/pahimar)

[Equivalent-Exchange-3](https://github.com/pahimar/Equivalent-Exchange-3)

I hope this can help you, to build a automation.

**Comment by ErythroCraft** [comment]
Have you got read the latest comment?

**Comment by Ramb0N05** [comment]
I've made it for 1.18.2: #11
I hope this is fine and runs stable

**Comment by ErythroCraft** [comment]
ok. I'll testing it at the weekend. Maybe you can do it for 1.19 too.

Have you got paypal?

**Comment by Ramb0N05** [comment]
I don't think any further changes to the code are necessary for this, but unfortunately I can't test this myself for 1.19 at the moment. I first created a pre-release in my fork so you can test it.

https://github.com/Ramb0N05/serversync-forge-loader/releases/tag/1.19.2-3.0.0-dev

**Comment by ErythroCraft** [comment]
ERROR by 1.19.2-3.0.0-dev 

[11:25:19] [Server thread/ERROR] [se.fo.lo.ServerSyncLoader/]: Failed to find ServerSync, have you added it to your minecraft folder?

Maybe I didn't understand, how to install this mod.
I putted the mod into the mods folder. Right?

But I don't know, why I must install the ServerSync mod, too.

**Comment by ErythroCraft** [comment]
I think you can do it simplier.

1. An server and client side mod in the mods folder will syncronized by login to any server.
2. The mod is creating a server mod folder e.g. - .minecraft/mods/server_name
3. saving the server mod list in the config file eg. - .minecraft/config/serversync_forge_loader.toml
4. an client side massage "Please restart your launcher to enable all updates"

Or I didn't understand how to install you plugin.

**Comment by rheimus** [comment]
The forge loader is only a loader for serversync via forge, you need serversync as that is the actual software that does anything.

A loader could theoretically be created for any of the modding engines, though that is only needed when you don't have enough server control to just run a script at startup.

**Comment by ErythroCraft** [comment]
ok
