### ISSUE TITLE
missing wildcard in src/main/java/serversync/forge/loader/ServerSyncLoader.java

### ISSUE THREAD

**Issue by arough007** [rheimus/serversync-forge-loader#3]
I noticed that the search for the syncserver.jar is not consistent with the release names.

orig:   ` .filter(f -> f.getFileName().toString().matches("serversync-\\d\\.\\d\\.\\d\\.jar"))`
fixed:  ` .filter(f -> f.getFileName().toString().matches("serversync-\\d\\.\\d\\.\\d\\*.jar"))`

The current version is named serversync-3.6.0-all.jar so it isn't found because of the "-all".
I think the above should fix it.

**Comment by arough007** [comment]
After looking into regex I found that a * wasn't the solution.
Especially not where I suggested to put it.
I modified the line and created a pull request #4

**Comment by rheimus** [comment]
Added extra conditions to match against alpha/beta versions and versions greater than a single digit
