### ISSUE TITLE
Start the serversync process earlier

### ISSUE THREAD

**Issue by alfuken** [rheimus/serversync-forge-loader#6]
Right now it starts when the forge server is almost done starting, with big modpacks this can take quite a long time. Is it possible to make serversync server start as soon as possible?..

**Comment by rheimus** [comment]
Possibly, would need to dig into the forge docs again to see if there is a way to suggest priority loading.

From what I recall you could only say "must be loaded before", as more of a way of loading your own libraries first.

There might also be an earlier lifecycle hook that we could plug the server start into.

**Comment by rheimus** [comment]
Moved SS start to the `AboutToStart` phase, this ends up being slightly earlier in the forge loading process 🤷‍♂️
